# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1114af4e4a17b8320fbe8748e802d875ddc9761d24269ddfc302961cf996fe44926c2547bf208a0a7ebdf95d95bd4c372ed9cdce2fc01c590b02a4cf1b1da536

test:
  secret_key_base: 179f35fb13c2748ea3351a20c5e8ca255545adcd0357d9fca507cb3860e8e3029da1c49e738c550aa0a0245583955394b275676f995de0ed486fe153f98fd1e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
